### ISSUE TITLE
ContainsWord should be covariant

### ISSUE THREAD

**Issue by GoogleCodeExporter** [seratch/scalatest#13]
```
I'm using version 2.9.2 of Scala and 1.8 of Scalatest.

And I have the following two test in a FunSuite with ShouldMatchers._ imported

    test("failure in variance, does not compile") {
        Set(new AnyRef, "x") should contain("x") // does not compile
    }

    test("failure in variance, compiles but is ugly") {
        Set(new AnyRef, "x") should contain("x".asInstanceOf[AnyRef])
    }

As noted in the comments the first one does not compile, while the second does.

I think the first one should compile just as fine and yield the same result as 
the second (a green test).

I looked briefly in the code, and it seems to me that in the class 

ContainWord in Matchers.scala 
http://code.google.com/p/scalatest/source/browse/trunk/src/main/scala/org/scalat
est/matchers/Matchers.scala

The apply method should be covariant in T, which probably means the Matcher 
should be covariant. 

But from looking at the definition of Matcher I found that it is actually 
contravariant, which means this works:

    test("this works but does it make sense") {
        Set("x") should contain(new AnyRef)
    }

But it doesn't make much sense I think.

```

Original issue reported on code.google.com by `schauder...@gmail.com` on 24 Nov 2012 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Matcher does need to be contravariant. For an explanation on why, scroll down 
to the "Matcher's variance" section of this page in ScalaTest's Scaladoc 
documentation:

http://www.artima.com/docs-scalatest-2.0.M5/#org.scalatest.matchers.Matcher

What would get you what you want is not a variance change, but just a loosening 
of the type constraint on the ContainWord.apply method. Instead of returning a 
Matcher[T] that could instead return a Matcher[Any]. The upside is that your 
example would compile without any cast, but the downside is so would checking 
whether a Set[Int] contained "x". I'm not sure what's better. Here's an example:

scala> import org.scalatest._
import org.scalatest._

scala> import matchers.ShouldMatchers._
import matchers.ShouldMatchers._

scala> import matchers.Matcher
import matchers.Matcher

scala> import matchers.MatchResult
import matchers.MatchResult

scala> import collection.GenTraversable
import collection.GenTraversable

scala> 

scala> def containAny(expectedElement: Any): Matcher[GenTraversable[Any]] = new 
Matcher[GenTraversable[Any]] {
     |   def apply(left: GenTraversable[Any]): MatchResult =
     |      MatchResult(
     |        left.exists(_ == expectedElement),
     |        left + " did not contain " + expectedElement,
     |        left + " contained " + expectedElement
     |      )
     |  }
containAny: (expectedElement: 
Any)org.scalatest.matchers.Matcher[scala.collection.GenTraversable[Any]]

scala> Set(new AnyRef, "x") should containAny ("x")

scala> Set(1, 2, 3) should containAny ("x")
org.scalatest.exceptions.TestFailedException: Set(1, 2, 3) did not contain x
    at org.scalatest.matchers.ClassicMatchers$class.newTestFailedException(Matchers.scala:158)
    at org.scalatest.matchers.ShouldMatchers$.newTestFailedException(ShouldMatchers.scala:2208)
    at org.scalatest.matchers.ShouldMatchers$ShouldMethodHelper$.shouldMatcher(ShouldMatchers.scala:888)
    at org.scalatest.matchers.ShouldMatchers$TraversableShouldWrapper.should(ShouldMatchers.scala:1568)
    at .<init>(<console>:18)
    at .<clinit>(<console>)
    at .<init>(<console>:11)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:704)
    at scala.tools.nsc.interpreter.IMain$Request$$anonfun$14.apply(IMain.scala:920)
    at scala.tools.nsc.interpreter.Line$$anonfun$1.apply$mcV$sp(Line.scala:43)
    at scala.tools.nsc.io.package$$anon$2.run(package.scala:25)
    at java.lang.Thread.run(Thread.java:680)

Note that the last one would not compile under the current scheme:

scala> Set(1, 2, 3) should contain ("x")
<console>:17: error: overloaded method value should with alternatives:
  (notWord: org.scalatest.matchers.ShouldMatchers.NotWord)org.scalatest.matchers.ShouldMatchers.ResultOfNotWordForTraversable[Int,scala.collection.GenTraversable[Int]] <and>
  (beWord: org.scalatest.matchers.ShouldMatchers.BeWord)org.scalatest.matchers.ShouldMatchers.ResultOfBeWordForAnyRef[scala.collection.GenTraversable[Int]] <and>
  (haveWord: org.scalatest.matchers.ShouldMatchers.HaveWord)org.scalatest.matchers.ShouldMatchers.ResultOfHaveWordForTraversable[Int] <and>
  (rightMatcher: org.scalatest.matchers.Matcher[scala.collection.GenTraversable[Int]])Unit
 cannot be applied to (org.scalatest.matchers.Matcher[scala.collection.GenTraversable[java.lang.String]])
              Set(1, 2, 3) should contain ("x")
                           ^

```

Original comment by `b...@artima.com` on 24 Nov 2012 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
One idea to avoid the cast is to make an any method that casts something to any:

scala> def any(o: Any): Any = o
any: (o: Any)Any

Then you could write:

scala> Set(new AnyRef, "x") should contain (any("x"))

```

Original comment by `b...@artima.com` on 24 Nov 2012 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
I understand the part about Matchers needing to be contravariant. I also 
understand why you don't like to make Set(1, 2, 3) should contain ("x") compile.

But 

Set(new AnyRef, "x") should contain ("x")

should really compile. In my case I'm testing a class which basically swallows 
all the type information of stuff contained in it, and in the end returns 
Set[AnyRef] having to cast around the test values is really annoying and makes 
people think they are doing something wrong (it did that to me).

What I'm not getting is: when the Type parameter T is bound to AnyRef in my 
example, why can't I pass as String, which inherits from AnyRef? Or to put it 
the other way round: Why is the type parameter bound to String when this 
doesn't compile, although binding it to AnyRef would make everything compile 
...? Maybe there is some wizardry using another Type parameter possible to make 
it work?

I'll use the 'any' workaround for now, thanks for that.
```

Original comment by `schauder...@gmail.com` on 24 Nov 2012 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
I'll ask around. See what folks prefer. It is possible we could just loosen it. 
It is actually over ambitious since some valid assertions don't pass the type 
checker. I know however that in the case of equality some people want 
assertions about equality to be more type restrictive. We're going to add some 
traits you can mix in to get that if you want. So we could also do that kind of 
approach, where by default it is less restrictive, so your example would 
compile. If someone is bugged by the fact that Set(1, 2, 3) should contain 
("x") passes the type checker, they could mix in the trait to get it more 
restrictive.
```

Original comment by `b...@artima.com` on 25 Nov 2012 at 12:08
